#!/usr/bin/env bash
# A script to installand configure Nginx on web01 server

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
