#!/usr/bin/env bash
# A script to configure Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "server {
		listen 80 default_server;
	        listen [::]:80 default_server;

		root /var/www/html;
		index index.html index.htm index.nginx-debian.html;

		server_name _;

		location /redirect_me {
			redirect 301 https://theweirdnerd.tech;
		}
	}" > /etc/nginx/sites-available/default
sudo service nginx restart
