#!/usr/bin/env bash
# A script that configures Nginx to listen on port 80
sudo service nginx start
echo -e " sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-enabled/default\n
sudo sed -i 's/listen \[::\]:8080/listen \[::\]:80/g' /etc/nginx/sites-enabled/default\n
service nginx restart" | bash
