#!/usr/bin/env bash
# A script that configures Nginx to listen on port 80
echo -e " sed -i 's/8080/80/' /etc/nginx/nginx.conf\n
sudo sed -i 's/8080/80/' /etc/nginx/sites-enabled/default\n
service nginx reload" | bash
