#!/usr/bin/env bash
# Script that:
#+ Creates the file /var/run/myscript.pid containing its PID
#+ Displays To infinity and beyond indefinitely
#+ Displays I hate the kill command when receiving a SIGTERM signal
#+ Displays Y U no love me?! when receiving a SIGINT signal
#+ Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

mkdir ~/var/run/myscript.pid
trap "I hate the kill command" SIGTERM
trap "Y U no love me?!" SIGINT
while true; do
	echo "To infinity and beyond"
	sleep 2
done
trap 'rm -rf ~/var/run/myscript.pid; exit' SIGQUIT SIGTERM
