#!/usr/bin/env bash
# A script that displays numbers from 1 to 100.
#+ Displays FizzBuzz when the number is a multiple of 3 and 5
#+ Displays Fizz when the number is multiple of 3
#+ Displays Buzz when the number is a multiple of 5
#+ Otherwise, displays the number
#+ In a list format
i=1
while [ $i -le 100 ]
do
	case $i in

	"(($i/15))")
	then
		echo "FizzBuzz"
		;;
	"(($i/3))")
	then
		echo "Fizz"
		;;
	"(($i/5))")
        then
                echo "Buzz"
                ;;
	esac

	echo "$i"
done
