#!/usr/bin/env bash
# A script that loops from 1 to 10 and:
#+ displays bad luck for the 4th loop iteration
#+ displays good luck for the 8th loop iteration
#+ displays Best School for the other iterations
i=0
while [ $i -le 9 ]
do
	((i++))
	if [ $i == 4 ]
	then
	    echo "bad luck"
	    continue
	elif [ $i == 8 ]
	then
	    echo "good luck"
	    continue
    	else
	echo "Best School"
	fi
done
