#!/usr/bin/env bash
# Script to change nginx privileges

sed -i "s/#user.+/user nginx/g" /etc/nginx/nginx.conf
echo "listen 8080" >> /etc/nginx/nginx.conf
echo "listen \[::\]:8080" >> /etc/nginx/nginx.conf
pgrep nginx -o > run/nginx.pid
sudo nginx -s reload
