#!/usr/bin/env bash
# Script to configure nginx priviledgesmade shorter

chmod 644 /etc/nginx/nginx.conf
sed -i "s/#user.+\;/user nginx;/g" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
pkill apache2
su nginx -s /bin/bash -c 'service nginx restart'
